export const ITEM_FIELD_MAP = {
  intake_batch_id: "intakeBatchId",
  purchase_id: "purchaseId",
  player_name: "playerName",
  manufacturer: "manufacturer",
  sport: "sport",
  team: "team",
  card_set: "set",
  card_number: "number",
  storage_location: "storageLocation",
  cost_basis: "costBasis",
  acquisition_date: "acquisitionDate",
  acquisition_source: "acquisitionSource",
  listing_status: "listingStatus",
  sale_status: "saleStatus",
  listed_on: "listedOn",
  front_img_id: "frontImgId",
  back_img_id: "backImgId",
  price_estimate: "priceEstimate",
  price_history: "priceHistory",
  market_price: "marketPrice",
  suggested_listing_price: "suggestedListingPrice",
  min_acceptable_price: "minAcceptablePrice",
  last_comp_price: "lastCompPrice",
  average_comp_price: "averageCompPrice",
  psa9_price: "psa9Price",
  psa10_price: "psa10Price",
  profit_realized: "profitRealized",
  sold_at: "soldAt",
  parallel_id: "parallelId",
  created_at: "createdAt",
  updated_at: "updatedAt",
  grading_candidate: "gradingCandidate",
  projected_grade: "projectedGrade",
  vault_status: "vaultStatus",
  condition_report: "conditionReport",
  cv_centering_lr: "cv_centering_lr",
  cv_centering_tb: "cv_centering_tb",
  cv_centering_score: "cv_centering_score",
  cv_processed: "cv_processed",
  ebay_centering: "ebay_centering",
  ebay_corner_sharpness: "ebay_corner_sharpness",
  ebay_edge_chipping: "ebay_edge_chipping",
};

export const SALE_FIELD_MAP = {
  card_id: "cardId",
  order_id: "orderId",
  card_name: "cardName",
  card_set: "cardSet",
  sale_price: "salePrice",
  cost_basis: "costBasis",
  buyer_handle: "buyerHandle",
  shipping_cost: "shippingCost",
  packaging_cost: "packagingCost",
  grading_cost: "gradingCost",
  tax_collected: "taxCollected",
  payout_amount: "payoutAmount",
  net_profit: "netProfit",
  listing_id: "listingId",
};

export const ORDER_FIELD_MAP = {
  sale_id: "saleId",
  listing_id: "listingId",
  item_id: "itemId",
  external_order_id: "externalOrderId",
  buyer_handle: "buyerHandle",
  sale_price: "salePrice",
  shipping_charge: "shippingCharge",
  tax_collected: "taxCollected",
  destination_country: "destinationCountry",
  destination_postal_code: "destinationPostalCode",
  payment_status: "paymentStatus",
  fulfillment_status: "fulfillmentStatus",
  sold_at: "soldAt",
  created_at: "createdAt",
  shipment_id: "shipmentId",
  tracking_number: "trackingNumber",
  label_url: "labelUrl",
  shipment_status: "shipmentStatus",
  service_level: "serviceLevel",
  shipped_at: "shippedAt",
};

export const LISTING_FIELD_MAP = {
  card_id: "cardId",
  external_listing_id: "externalListingId",
  card_name: "cardName",
  card_set: "cardSet",
  card_number: "cardNumber",
  listing_title: "listingTitle",
  listing_description: "listingDescription",
  category_path: "categoryPath",
  item_specifics: "itemSpecifics",
  shipping_profile: "shippingProfile",
  image_count: "imageCount",
  automation_state: "automationState",
  pricing_strategy: "pricingStrategy",
  publish_status: "publishStatus",
  start_price: "startPrice",
  buy_now_price: "buyNowPrice",
  auction_end_date: "auctionEndDate",
  shipping_weight_oz: "shippingWeightOz",
  export_batch_id: "exportBatchId",
  current_bid: "currentBid",
  sold_price: "soldPrice",
  sold_date: "soldDate",
  created_at: "createdAt",
};
